### ISSUE TITLE
<optgroup> Support ?

### ISSUE THREAD

**Issue by mysoko** [localytics/angular-chosen#113] opened 2015-03-29 05:50 UTC
![image](https://cloud.githubusercontent.com/assets/75619/6884257/8c89a6a8-d61a-11e4-9dce-b53440af21c4.png)

Do not see how the grouping configuration?

**Comment by dkavanagh** [comment] 2015-04-10 18:49
I've used optgroup, but notice it doesn't work. The model gets a value that's off-by-one on the 2nd selection.

**Comment by posva** [comment] 2015-05-11 09:23
You can actually build the options like this:
```js
ng-options="sa.id as sa.name group by sa.group for sa in availableServicesApps"
```
but this doesn't solve the problem. There is still some kind of offset issue.

**This should be marked as a bug**
Here is how to reproduce it
```js
// controller
$scope.list = [
  { name: 'value 1', id: 1, group: 'group 1' },
  { name: 'value 2', id: 2, group: 'group 2' }
];
```
```html
// some html
<select chosen="chosen" ng-options="o.id as o.name group by o.group for o in list"></select>
```

Select `value 1` then select `value 2`. You will get an error on console. The first selected options cannot be changed.

Also adding some information on the `README.md` migth help newcomers

**Comment by dkavanagh** [comment] 2015-05-11 11:51
I found that Angular1.4 seemed to solve this problem, but introduced other issues with our application due to the way option values are set. So, not clear this is totally a chosen-related.

**Comment by posva** [comment] 2015-05-11 11:56
Using chosen works well, it looks like the combination bring up this error :confused:

**Comment by dkavanagh** [comment] 2015-05-12 19:02
Even in angular 1.3, I see an off-by-1 error on the 2nd selection without optgroups, so maybe I'll open a separate bug.

**Comment by damoeb** [comment] 2016-01-20 13:21
Our workaround was adding a empty option field.

<select chosen ng-model="wizard.step.ud.SCHEDULE_MULTIPLE.duration.minute" ng-options="m.index as m.value for m in wizard.step.minutes" > <option value=""></option> </select>

**Comment by leocaseiro** [comment] 2016-02-25 23:54
Duplicated of #47

**Closed by leocaseiro** 2016-02-25 23:54 UTC
